### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by alexanderjophus** [JMS55/bevy_dioxus#22]
Hey (me again), wondering if it's possible to add a README.md file.

Happy to contribute it too. Something like this;

# bevy_dioxus
crates.io badge / license badges

## Installation
Add the following to your `Cargo.toml`:

```toml
[dependencies]
bevy_dioxus = { git = "https://github.com/JMS55/bevy_dioxus" }
```

## Usage

```rust
fn some_example
```
